In [1]:
import torch

torch.cuda.is_available()

c:\Users\pablo\Desktop\Pablo\Programación\LLMs-from-scratch\LLM-env\Lib\site-packages\torch\_subclasses\functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


True

## One-hot Encoding

In [3]:
def to_onehot(y, num_classes):
    y_onehot = torch.zeros(y.size(0), num_classes)
    y_onehot.scatter_(1, y.view(-1,1).long(), 1).float()
    return y_onehot

y = torch.tensor([0, 1, 2, 2])

y_enc = to_onehot(y, 3)

print('one-hot encoding:\n', y_enc)

one-hot encoding:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])


## Softmax
Suppose we have some net imputs Z, where each row is a sample and each column is a class.

In [6]:
Z = torch.tensor( [[-0.3,  -0.5, -0.5],
                   [-0.4,  -0.1, -0.5],
                   [-0.3,  -0.94, -0.5],
                   [-0.99, -0.88, -0.5]])

def softmax(z):
    return (torch.exp(z.t()) / torch.sum(torch.exp(z), dim =1)).t()

smax = softmax(Z)
print('softmax:\n', smax)

softmax:
 tensor([[0.3792, 0.3104, 0.3104],
        [0.3072, 0.4147, 0.2780],
        [0.4263, 0.2248, 0.3490],
        [0.2668, 0.2978, 0.4354]])


The probabilities can then be converted to class labels based on the largest probability in each row.

In [7]:
def to_classlabel(z):
    return torch.argmax(z, dim =1)

print('predicted class labels: ', to_classlabel(smax))
print('true class labels: ', to_classlabel(y_enc))

predicted class labels:  tensor([0, 1, 0, 2])
true class labels:  tensor([0, 1, 2, 2])


## Cross Entropy

In [8]:
def cross_entropy(softmax, y_target):
    return - torch.sum(y_target * torch.log(softmax), dim =1)

xent = cross_entropy(smax, y_enc)
print('Cross Entropy:', xent)

Cross Entropy: tensor([0.9698, 0.8801, 1.0527, 0.8314])


## In PyTorch

In [9]:
import torch.nn.functional as F

F.nll_loss(torch.log(smax), y, reduction = 'none')

tensor([0.9698, 0.8801, 1.0527, 0.8314])

In [10]:
F.cross_entropy(Z,y, reduction='none') 

tensor([0.9698, 0.8801, 1.0527, 0.8314])